

const TYPES = {
    GET_POKEMONS: "GET_POKEMONS",
    GET_TYPES: "GET_TYPES",
    GET_USER: "GET_USER",
    HANDLE_SORT: "HANDLE_SORT",
    FILTER_BY_CREATED: 'FILTER_BY_CREATED',
    FILTERED_BY_TYPE: 'FILTERED_BY_TYPE',
    GET_NAME_POKEMON: "GET_NAME_POKEMON",
    GET_DETAIL: "GET_DETAIL",
    POST_POKEMON: "POST_POKEMON"
}


export default TYPES;